### ISSUE TITLE
Sql Error

### ISSUE THREAD

**Issue by VickyKumar2804** [StevenFlecha/Sendy_listcleaner_mod#1]
1. SQL query:
   CREATE TABLE IF NOT EXISTS flecha_mods (
   id INT(11) NOT NULL AUTO_INCREMENT,
   modname VARCHAR(40) NOT NULL,
   install_date datetime default NOW(),
   PRIMARY KEY (`id`)
   )ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
   MySQL said: Documentation
#1067 - Invalid default value for 'install_date'
1. CREATE TABLE IF NOT EXISTS `flecha_activity_log` (
   id INT(11) NOT NULL AUTO_INCREMENT,
   subid INT(11) NOT NULL,
   ownerid INT(11) NOT NULL,
   last_clicked datetime default NULL,
   last_opened datetime default NULL,
   PRIMARY KEY (`id`),
   KEY `subid` (`subid`),
   KEY `userID` (`userID`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
   MySQL said: Documentation
#1072 - Key column 'userID' doesn't exist in table

**Comment by StevenFlecha** [comment]
1: probably your version of Mysql works fine on 10.1.4-MariaDB
Just change NOW() with CURRENT_TIMESTAMP that should solve it.

2: yeah thats an error. Replace
KEY `userID` (`userID`) with
KEY `userID` (`ownerid`)
